title: Jekyll URL Shortener
description: URL Shorteners with Jekyll and GitHub Pages.
include: [".htaccess"]
exclude: ["README.md", "LICENSE.md"]
timezone: America/Edmonton
encoding: UTF-8
fathom_analytics: XXTESXHY

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#site.url: https://a8m.io
#site.baseurl: /
